//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class analysisReference
    {
        public int id { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public Nullable<int> minAge { get; set; }
        public Nullable<int> maxAge { get; set; }
        public Nullable<double> minValue { get; set; }
        public Nullable<double> maxValue { get; set; }
        public string type { get; set; }
        public string description { get; set; }
        public Nullable<int> analysisTypeId { get; set; }
    }
}
