//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentAvailability
    {
        public int id { get; set; }
        public Nullable<int> doctorId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string startTime { get; set; }
        public string endTime { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
