//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int id { get; set; }
        public string identityNumber { get; set; }
        public int sectionId { get; set; }
        public int hospitalId { get; set; }
        public string title { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string photoImageSource { get; set; }
    
        public virtual Hospital Hospital { get; set; }
        public virtual Section Section { get; set; }
        public virtual Users Users { get; set; }
    }
}
