//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auth.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EksaProjectEntities : DbContext
    {
        public EksaProjectEntities()
            : base("name=EksaProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<analysisAdvice> analysisAdvice { get; set; }
        public virtual DbSet<analysisInfo> analysisInfo { get; set; }
        public virtual DbSet<analysisReference> analysisReference { get; set; }
        public virtual DbSet<analysisType> analysisType { get; set; }
        public virtual DbSet<analysisValues> analysisValues { get; set; }
        public virtual DbSet<AppointmentAvailability> AppointmentAvailability { get; set; }
        public virtual DbSet<AppointmentHistory> AppointmentHistory { get; set; }
        public virtual DbSet<Assay> Assay { get; set; }
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<Hospital> Hospital { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Section> Section { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Medicine> Medicine { get; set; }
        public virtual DbSet<MedicineReminder> MedicineReminder { get; set; }
    }
}
