//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineReminder
    {
        public int id { get; set; }
        public string identityNumber { get; set; }
        public int medicineId { get; set; }
        public System.DateTime start { get; set; }
        public int day { get; set; }
        public string clock { get; set; }
        public int reuse { get; set; }
        public bool used { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Users Users { get; set; }
    }
}
