//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int id { get; set; }
        public string identityNumber { get; set; }
        public Nullable<int> assayId { get; set; }
    
        public virtual Assay Assay { get; set; }
    }
}
