//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Assay = new HashSet<Assay>();
            this.Doctor = new HashSet<Doctor>();
            this.Login = new HashSet<Login>();
            this.MedicineReminder = new HashSet<MedicineReminder>();
        }
    
        public int id { get; set; }
        public string userIdentityNumber { get; set; }
        public string userPersonalName { get; set; }
        public string userPersonalSurname { get; set; }
        public string userPassword { get; set; }
        public string userPhoneNumber { get; set; }
        public string userEmail { get; set; }
        public string userImageSource { get; set; }
        public System.DateTime userBirthDate { get; set; }
        public int userRol { get; set; }
        public bool isActivity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assay> Assay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor> Doctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login> Login { get; set; }
        public virtual Rol Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicineReminder> MedicineReminder { get; set; }
    }
}
